### ISSUE TITLE
bot failed to bucket many labels into `lib / src`

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/github-bot#137]
See https://github.com/nodejs/node/pull/12366

cc @mscdex

**Comment by phillipj** [comment]
This is because `lib / src` label bucket/limiter is exclusively done for files in `lib/`. Most interesting code is in [matchSubSystemsByRegex()](https://github.com/nodejs/github-bot/blob/master/lib/node-labels.js#L218) and [hasJsSubsystemChanges](https://github.com/nodejs/github-bot/blob/master/lib/node-labels.js#L240).

I take it that's wrong, so I started on a fix: https://github.com/nodejs/github-bot/pull/141
