### ISSUE TITLE
Bot doesn't comment in PRs when autostarting CI

### ISSUE THREAD

**Issue by richardlau** [nodejs/github-bot#175]
As per https://github.com/nodejs/github-bot/pull/173#discussion_r192500341 currently the Bot doesn't comment in PRs when autostarting CI.

If we start relying on the autostarted CI rather than manual runs, then if we land PRs without merging no evidence will be left that CI was run at all.

**Comment by phillipj** [comment]
@maclover7 would you mind elaborating a bit what you meant with "faulty Jenkins logic"? Is this is flaw in the bot or how Jenkins reports build statuses?

**Comment by maclover7** [comment]
@richardlau @phillipj Sorry for not being more specific -- this is a flaw in how ci.nodejs.org works. The way the CITGM logic works is because Jenkins will redirect to the newly created job after creation. This does not happen for node-test-pull-request-lite since it is not a pipeline job, it only redirects to the job's "home page". I will be taking a look to converting the lite job to a pipeline in the coming days

**Comment by phillipj** [comment]
Ahh thanks, good to hear improvements are on the way 👍

**Comment by maclover7** [comment]
Fixed in #178, #180
