### ISSUE TITLE
create meeting issues

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/github-bot#2]
from https://github.com/williamkapke/hookbot/issues/2

we need something that uses something like https://github.com/rvagg/make-node-meeting (which relies on https://github.com/rvagg/node-meeting-agenda) to automatically make agenda issues every week, so that Rod doesn't have to lol

**Comment by williamkapke** [comment]
[I've been hoping to get a Google Calendar going](https://github.com/nodejs/TSC/issues/63) that keeps track of all the meetings. Since some like the TSC & CTC are recurring (for now), I've been trying to figure out what would kick off creating the agenda issues X number of days before the meeting...? Ideas?

Maybe to make it **super awesome** we could also emit events from [Google Calendar push notifications API](https://developers.google.com/google-apps/calendar/v3/push). Then, for example, to create & cancel a meetings it could be done via the Google calendar and the bot could update the issue(s).

**Comment by Trott** [comment]
Michael Dawson set up a job to create meeting issues so it isn't done manually anymore.
