### ISSUE TITLE
Request: don't comment on error

### ISSUE THREAD

**Issue by cjihrig** [nodejs/github-bot#238]
> Sadly, an error occurred when I tried to trigger a build. :(

These comments don't really add value to GitHub threads, create additional notification spam, and are likely confusing for newcomers. Is it possible for the bot to just not comment, and instead email (or otherwise notify) bot maintainers when errors occur.

**Comment by phillipj** [comment]
I see your point indeed. Too busy at work to fix it ASAP, but anyone feel free to only invoke `createPrComment()` on successes about here: [./scripts/trigger-jenkins-build.js#L97](https://github.com/nodejs/github-bot/blob/e782b556d9ab065c8f4a24ab054af2eaf1ce16db/scripts/trigger-jenkins-build.js#L97).

[github-bot at nodejs.org](https://github.com/nodejs/email/blob/master/iojs.org/aliases.json#L214) might be suitable?

**Comment by refack** [comment]
We could make these into a Status API call, which is less intrusive...

**Comment by phillipj** [comment]
True @refack. As a bot maintainer I appreciated getting noticed by collaborators when something starts to fail, but getting an email *every* time will be quite annoying. Guess that annoyance is in practise what feature request is all about, just with PR comments rather than emails.

Posting a failed status via the Status API like we do for Jenkins job statuses today, would bring the point across and allow collaborators to open an issue in this repo or contact bot maintainers somehow.

On second thought, only sending that email, wouldn't let the collaborators know there's currently some issues kicking off Jenkins builds. It would rather be that nothing happens, which I assume would cause more confusion and uncertainty than getting _some kind_ of feedback about the failure from the bot's point of view.

**Comment by phillipj** [comment]
For ref now that https://github.com/nodejs/github-bot/pull/228 just rolled out, the bot should start re-using / edit its previous PR comment, which I'm assuming will also help a lot to reduce the previous comment noise it has generated.

**Comment by richardlau** [comment]
> 
> 
> For ref now that #228 just rolled out, the bot should start re-using / edit its previous PR comment, which I'm assuming will also help a lot to reduce the previous comment noise it has generated.

I kicked off https://ci.nodejs.org/job/node-test-pull-request/23781/ for https://github.com/nodejs/node/pull/28128 but the bot doesn't appear to have updated either of the two comments it previously made in that PR.

**Comment by phillipj** [comment]
Thanks @richardlau! Found this in the logs:

```
00:42:03.038Z ERROR bot: Error while creating comment on GitHub (req_id=baae5340-8be1-11e9-a4d0-856e0a231c31)
    GraphqlError: Variable number of type Int! was provided invalid value
        at request.then.response (/home/../node_modules/@octokit/graphql/lib/graphql.js:31:15)
```

I'll dive into this to see what might be causing it..

**Comment by phillipj** [comment]
Rolled a couple of improvements (2488a2bc8c7ce9a7d123767bbfe65b139928675b, 98f7322d1678b7e7b1a2610533371293fe5930d2) which should either fix the issue or give more detailed info about what/when failed.

**Comment by richardlau** [comment]
Started https://ci.nodejs.org/job/node-test-pull-request-lite-pipeline/3673/ for https://github.com/nodejs/node/pull/28178. No edit/update in the issue from the bot.

**Comment by phillipj** [comment]
Soooo #241 rolled out today, which removed the error comments completely for now.

That's still not ideal as bot maintainers really do need a hint about these kinds of failures when they start happening. Building upon https://github.com/nodejs/github-bot/issues/238#issuecomment-499498663 about using the Status API to report these failures, is that something that potentially could break node-core-utils @joyeecheung? Or isn't statuses used there at all?
